//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//
package it.cnr.isti.giove.ctt;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ConditionGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="ConditionGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="2">
 *         &lt;element name="ConditionGroup" type="{http://giove.isti.cnr.it/ctt}ConditionGroup"/>
 *         &lt;element name="ConditionLiteral" type="{http://giove.isti.cnr.it/ctt}ConditionLiteral"/>
 *       &lt;/choice>
 *       &lt;attribute name="operator" type="{http://giove.isti.cnr.it/ctt}BinaryOperator" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionGroup", propOrder = {
    "conditionGroupOrConditionLiteral"
})
public class ConditionGroup {

    @JsonTypeInfo(
      use = JsonTypeInfo.Id.NAME,
      include= JsonTypeInfo.As.WRAPPER_OBJECT,
      property = "conditionGroupOrConditionLiteral"
    )    
    @JsonSubTypes({
        @JsonSubTypes.Type(value = ConditionLiteral.class, name="ConditionLiteral"),
        @JsonSubTypes.Type(value = ConditionGroup.class, name="ConditionGroup"),
        })    
    @XmlElements({
        @XmlElement(name = "ConditionLiteral", type = ConditionLiteral.class),
        @XmlElement(name = "ConditionGroup", type = ConditionGroup.class)
    })
    protected List<java.lang.Object> conditionGroupOrConditionLiteral;
    @XmlAttribute
    protected BinaryOperator operator;

    /**
     * Gets the value of the conditionGroupOrConditionLiteral property.
     *
     * <p> This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the conditionGroupOrConditionLiteral
     * property.
     *
     * <p> For example, to add a new item, do as follows:
     * <pre>
     *    getConditionGroupOrConditionLiteral().add(newItem);
     * </pre>
     *
     *
     * <p> Objects of the following type(s) are allowed in the list      {@link ConditionLiteral }
     * {@link ConditionGroup }
     *
     *
     */
    public List<java.lang.Object> getConditionGroupOrConditionLiteral() {
        if (conditionGroupOrConditionLiteral == null) {
            conditionGroupOrConditionLiteral = new ArrayList<java.lang.Object>();
        }
        return this.conditionGroupOrConditionLiteral;
    }

    /**
     * Gets the value of the operator property.
     *
     * @return possible object is {@link BinaryOperator }
     *
     */
    public BinaryOperator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     *
     * @param value allowed object is {@link BinaryOperator }
     *
     */
    public void setOperator(BinaryOperator value) {
        this.operator = value;
    }
}
