//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://giove.isti.cnr.it/cttcoop}Belong"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "belong"
})
@XmlRootElement(name = "Connection", namespace = "http://giove.isti.cnr.it/cttcoop")
public class Connection {

    @XmlElement(name = "Belong", namespace = "http://giove.isti.cnr.it/cttcoop", required = true)
    protected Belong belong;

    /**
     * Gets the value of the belong property.
     * 
     * @return
     *     possible object is
     *     {@link Belong }
     *     
     */
    public Belong getBelong() {
        return belong;
    }

    /**
     * Sets the value of the belong property.
     * 
     * @param value
     *     allowed object is
     *     {@link Belong }
     *     
     */
    public void setBelong(Belong value) {
        this.belong = value;
    }

}
