//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.codehaus.jackson.map.annotate.JsonDeserialize;


/**
 * <p>Java class for Object complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Object">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Platform" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InputAction" type="{http://giove.isti.cnr.it/ctt}InputAction"/>
 *         &lt;element name="OutputAction" type="{http://giove.isti.cnr.it/ctt}OutputAction"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" use="required" type="{http://giove.isti.cnr.it/ctt}ObjectClass" />
 *       &lt;attribute name="type" use="required" type="{http://giove.isti.cnr.it/ctt}ObjectType" />
 *       &lt;attribute name="access_mode" use="required" type="{http://giove.isti.cnr.it/ctt}ObjectAccess" />
 *       &lt;attribute name="cardinality" use="required" type="{http://giove.isti.cnr.it/ctt}ObjectCardinality" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Object", propOrder = {
    "platform",
    "inputAction",
    "outputAction"
})
public class Object {
    @JsonDeserialize(contentAs=String.class)
    @XmlElement(name = "Platform")
    protected List<String> platform;
    @XmlElement(name = "InputAction", required = true)
    protected InputAction inputAction;
    @XmlElement(name = "OutputAction", required = true)
    protected OutputAction outputAction;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(name = "class", required = true)
    protected ObjectClass clazz;
    @XmlAttribute(required = true)
    protected ObjectType type;
    @XmlAttribute(name = "access_mode", required = true)
    protected ObjectAccess accessMode;
    @XmlAttribute(required = true)
    protected ObjectCardinality cardinality;

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<String>();
        }
        return this.platform;
    }

    /**
     * Gets the value of the inputAction property.
     * 
     * @return
     *     possible object is
     *     {@link InputAction }
     *     
     */
    public InputAction getInputAction() {
        return inputAction;
    }

    /**
     * Sets the value of the inputAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputAction }
     *     
     */
    public void setInputAction(InputAction value) {
        this.inputAction = value;
    }

    /**
     * Gets the value of the outputAction property.
     * 
     * @return
     *     possible object is
     *     {@link OutputAction }
     *     
     */
    public OutputAction getOutputAction() {
        return outputAction;
    }

    /**
     * Sets the value of the outputAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputAction }
     *     
     */
    public void setOutputAction(OutputAction value) {
        this.outputAction = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectClass }
     *     
     */
    public ObjectClass getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectClass }
     *     
     */
    public void setClazz(ObjectClass value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectType }
     *     
     */
    public ObjectType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectType }
     *     
     */
    public void setType(ObjectType value) {
        this.type = value;
    }

    /**
     * Gets the value of the accessMode property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectAccess }
     *     
     */
    public ObjectAccess getAccessMode() {
        return accessMode;
    }

    /**
     * Sets the value of the accessMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectAccess }
     *     
     */
    public void setAccessMode(ObjectAccess value) {
        this.accessMode = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectCardinality }
     *     
     */
    public ObjectCardinality getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectCardinality }
     *     
     */
    public void setCardinality(ObjectCardinality value) {
        this.cardinality = value;
    }

}
