//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.isti.giove.ctt package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cardinality_QNAME = new QName("http://giove.isti.cnr.it/cttcoop", "Cardinality");
    private final static QName _Comments_QNAME = new QName("http://giove.isti.cnr.it/cttcoop", "Comments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.isti.giove.ctt
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimePerformance }
     * 
     */
    public TimePerformance createTimePerformance() {
        return new TimePerformance();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Belong }
     * 
     */
    public Belong createBelong() {
        return new Belong();
    }

    /**
     * Create an instance of {@link ConditionGroup }
     * 
     */
    public ConditionGroup createConditionGroup() {
        return new ConditionGroup();
    }

    /**
     * Create an instance of {@link TaskModelCOOP }
     * 
     */
    public TaskModelCOOP createTaskModelCOOP() {
        return new TaskModelCOOP();
    }

    /**
     * Create an instance of {@link Cooperation }
     * 
     */
    public Cooperation createCooperation() {
        return new Cooperation();
    }

    /**
     * Create an instance of {@link TaskCONN }
     * 
     */
    public TaskCONN createTaskCONN() {
        return new TaskCONN();
    }

    /**
     * Create an instance of {@link SubTaskCOOP }
     * 
     */
    public SubTaskCOOP createSubTaskCOOP() {
        return new SubTaskCOOP();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link SiblingRight }
     * 
     */
    public SiblingRight createSiblingRight() {
        return new SiblingRight();
    }

    /**
     * Create an instance of {@link SiblingLeft }
     * 
     */
    public SiblingLeft createSiblingLeft() {
        return new SiblingLeft();
    }

    /**
     * Create an instance of {@link TaskModel }
     * 
     */
    public TaskModel createTaskModel() {
        return new TaskModel();
    }

    /**
     * Create an instance of {@link InputAction }
     * 
     */
    public InputAction createInputAction() {
        return new InputAction();
    }

    /**
     * Create an instance of {@link OutputAction }
     * 
     */
    public OutputAction createOutputAction() {
        return new OutputAction();
    }

    /**
     * Create an instance of {@link TaskCOOP }
     * 
     */
    public TaskCOOP createTaskCOOP() {
        return new TaskCOOP();
    }

    /**
     * Create an instance of {@link SubTask }
     * 
     */
    public SubTask createSubTask() {
        return new SubTask();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link COOPConcurTaskTrees }
     * 
     */
    public COOPConcurTaskTrees createCOOPConcurTaskTrees() {
        return new COOPConcurTaskTrees();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link TemporalOperator }
     * 
     */
    public TemporalOperator createTemporalOperator() {
        return new TemporalOperator();
    }

    /**
     * Create an instance of {@link ConditionLiteral }
     * 
     */
    public ConditionLiteral createConditionLiteral() {
        return new ConditionLiteral();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://giove.isti.cnr.it/cttcoop", name = "Cardinality")
    public JAXBElement<String> createCardinality(String value) {
        return new JAXBElement<String>(_Cardinality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://giove.isti.cnr.it/cttcoop", name = "Comments")
    public JAXBElement<String> createComments(String value) {
        return new JAXBElement<String>(_Comments_QNAME, String.class, null, value);
    }

}
