//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://giove.isti.cnr.it/cttcoop}TaskCOOP" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://giove.isti.cnr.it/cttcoop}TaskCONN" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taskCOOPOrTaskCONN"
})
@XmlRootElement(name = "SubTaskCOOP", namespace = "http://giove.isti.cnr.it/cttcoop")
public class SubTaskCOOP {

    @XmlElements({
        @XmlElement(name = "TaskCOOP", namespace = "http://giove.isti.cnr.it/cttcoop", type = TaskCOOP.class),
        @XmlElement(name = "TaskCONN", namespace = "http://giove.isti.cnr.it/cttcoop", type = TaskCONN.class)
    })
    protected List<java.lang.Object> taskCOOPOrTaskCONN;

    /**
     * Gets the value of the taskCOOPOrTaskCONN property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskCOOPOrTaskCONN property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskCOOPOrTaskCONN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskCOOP }
     * {@link TaskCONN }
     * 
     * 
     */
    public List<java.lang.Object> getTaskCOOPOrTaskCONN() {
        if (taskCOOPOrTaskCONN == null) {
            taskCOOPOrTaskCONN = new ArrayList<java.lang.Object>();
        }
        return this.taskCOOPOrTaskCONN;
    }

}
