//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://giove.isti.cnr.it/cttcoop}TaskCOOP"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NameTaskModelID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taskCOOP"
})
@XmlRootElement(name = "TaskModelCOOP", namespace = "http://giove.isti.cnr.it/cttcoop")
public class TaskModelCOOP {

    @XmlElement(name = "TaskCOOP", namespace = "http://giove.isti.cnr.it/cttcoop", required = true)
    protected TaskCOOP taskCOOP;
    @XmlAttribute(name = "NameTaskModelID", required = true)
    protected String nameTaskModelID;

    /**
     * Gets the value of the taskCOOP property.
     * 
     * @return
     *     possible object is
     *     {@link TaskCOOP }
     *     
     */
    public TaskCOOP getTaskCOOP() {
        return taskCOOP;
    }

    /**
     * Sets the value of the taskCOOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskCOOP }
     *     
     */
    public void setTaskCOOP(TaskCOOP value) {
        this.taskCOOP = value;
    }

    /**
     * Gets the value of the nameTaskModelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameTaskModelID() {
        return nameTaskModelID;
    }

    /**
     * Sets the value of the nameTaskModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameTaskModelID(String value) {
        this.nameTaskModelID = value;
    }

}
