//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for Task complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Task">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Platform" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Precondition" type="{http://giove.isti.cnr.it/ctt}ConditionGroup"/>
 *         &lt;element name="Postcondition" type="{http://giove.isti.cnr.it/ctt}ConditionGroup"/>
 *         &lt;element name="TemporalOperator" type="{http://giove.isti.cnr.it/ctt}TemporalOperator" minOccurs="0"/>
 *         &lt;element name="TimePerformance" type="{http://giove.isti.cnr.it/ctt}TimePerformance"/>
 *         &lt;element name="Parent" type="{http://giove.isti.cnr.it/ctt}Parent" minOccurs="0"/>
 *         &lt;element name="SiblingLeft" type="{http://giove.isti.cnr.it/ctt}SiblingLeft" minOccurs="0"/>
 *         &lt;element name="SiblingRight" type="{http://giove.isti.cnr.it/ctt}SiblingRight" minOccurs="0"/>
 *         &lt;element name="Object" type="{http://giove.isti.cnr.it/ctt}Object" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SubTask" type="{http://giove.isti.cnr.it/ctt}SubTask" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Category" use="required" type="{http://giove.isti.cnr.it/ctt}Category" />
 *       &lt;attribute name="Iterative" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Optional" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PartOfCooperation" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Frequency" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Task", propOrder = {
    "name",
    "type",
    "description",
    "platform",
    "context",
    "precondition",
    "postcondition",
    "temporalOperator",
    "timePerformance",
    "parent",
    "siblingLeft",
    "siblingRight",
    "object",
    "subTask"
})
public class Task {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @JsonDeserialize(contentAs=String.class)
    @XmlElement(name = "Platform")
    protected List<String> platform;
    @XmlElement(name = "Context", required = true)
    protected String context;
    @XmlElement(name = "Precondition", required = true)
    protected ConditionGroup precondition;
    @XmlElement(name = "Postcondition", required = true)
    protected ConditionGroup postcondition;
    @XmlElement(name = "TemporalOperator")
    protected TemporalOperator temporalOperator;
    @XmlElement(name = "TimePerformance", required = true)
    protected TimePerformance timePerformance;
    @XmlElement(name = "Parent")
    protected Parent parent;
    @XmlElement(name = "SiblingLeft")
    protected SiblingLeft siblingLeft;
    @XmlElement(name = "SiblingRight")
    protected SiblingRight siblingRight;
    @JsonDeserialize(contentAs=Object.class)
    @XmlElement(name = "Object")
    protected List<Object> object;    
    @XmlElement(name = "SubTask")
    protected SubTask subTask;
    @XmlAttribute(name = "Identifier", required = true)
    protected String identifier;
    @XmlAttribute(name = "Category", required = true)
    protected Category category;
    @XmlAttribute(name = "Iterative", required = true)
    protected boolean iterative;
    @XmlAttribute(name = "Optional", required = true)
    protected boolean optional;
    @XmlAttribute(name = "PartOfCooperation", required = true)
    protected boolean partOfCooperation;
    @XmlAttribute(name = "Frequency", required = true)
    protected String frequency;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public String getContext() {
        return context;
    }
    
    public void setContext(String value) {
        this.context = value;
    }
    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<String>();
        }
        return this.platform;
    }

    /**
     * Gets the value of the precondition property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionGroup }
     *     
     */
    public ConditionGroup getPrecondition() {
        return precondition;
    }

    /**
     * Sets the value of the precondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionGroup }
     *     
     */
    public void setPrecondition(ConditionGroup value) {
        this.precondition = value;
    }

    /**
     * Gets the value of the postcondition property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionGroup }
     *     
     */
    public ConditionGroup getPostcondition() {
        return postcondition;
    }

    /**
     * Sets the value of the postcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionGroup }
     *     
     */
    public void setPostcondition(ConditionGroup value) {
        this.postcondition = value;
    }

    /**
     * Gets the value of the temporalOperator property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalOperator }
     *     
     */
    public TemporalOperator getTemporalOperator() {
        return temporalOperator;
    }

    /**
     * Sets the value of the temporalOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalOperator }
     *     
     */
    public void setTemporalOperator(TemporalOperator value) {
        this.temporalOperator = value;
    }

    /**
     * Gets the value of the timePerformance property.
     * 
     * @return
     *     possible object is
     *     {@link TimePerformance }
     *     
     */
    public TimePerformance getTimePerformance() {
        return timePerformance;
    }

    /**
     * Sets the value of the timePerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePerformance }
     *     
     */
    public void setTimePerformance(TimePerformance value) {
        this.timePerformance = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link Parent }
     *     
     */
    public Parent getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parent }
     *     
     */
    public void setParent(Parent value) {
        this.parent = value;
    }

    /**
     * Gets the value of the siblingLeft property.
     * 
     * @return
     *     possible object is
     *     {@link SiblingLeft }
     *     
     */
    public SiblingLeft getSiblingLeft() {
        return siblingLeft;
    }

    /**
     * Sets the value of the siblingLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiblingLeft }
     *     
     */
    public void setSiblingLeft(SiblingLeft value) {
        this.siblingLeft = value;
    }

    /**
     * Gets the value of the siblingRight property.
     * 
     * @return
     *     possible object is
     *     {@link SiblingRight }
     *     
     */
    public SiblingRight getSiblingRight() {
        return siblingRight;
    }

    /**
     * Sets the value of the siblingRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiblingRight }
     *     
     */
    public void setSiblingRight(SiblingRight value) {
        this.siblingRight = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getObject() {
        if (object == null) {
            object = new ArrayList<Object>();
        }
        return this.object;
    }

    /**
     * Gets the value of the subTask property.
     * 
     * @return
     *     possible object is
     *     {@link SubTask }
     *     
     */
    public SubTask getSubTask() {
        return subTask;
    }

    /**
     * Sets the value of the subTask property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubTask }
     *     
     */
    public void setSubTask(SubTask value) {
        this.subTask = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the iterative property.
     * 
     */
    public boolean isIterative() {
        return iterative;
    }

    /**
     * Sets the value of the iterative property.
     * 
     */
    public void setIterative(boolean value) {
        this.iterative = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     */
    public boolean isOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     */
    public void setOptional(boolean value) {
        this.optional = value;
    }

    /**
     * Gets the value of the partOfCooperation property.
     * 
     */
    public boolean isPartOfCooperation() {
        return partOfCooperation;
    }

    /**
     * Sets the value of the partOfCooperation property.
     * 
     */
    public void setPartOfCooperation(boolean value) {
        this.partOfCooperation = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

}
