//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.17 at 01:02:19 PM CEST 
//


package it.cnr.isti.giove.ctt;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemporalOperatorName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TemporalOperatorName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="SequentialEnabling"/>
 *     &lt;enumeration value="Disabling"/>
 *     &lt;enumeration value="Choice"/>
 *     &lt;enumeration value="Interleaving"/>
 *     &lt;enumeration value="InterleavingInfo"/>
 *     &lt;enumeration value="Synchronization"/>
 *     &lt;enumeration value="SuspendResume"/>
 *     &lt;enumeration value="SequentialEnablingInfo"/>
 *     &lt;enumeration value="OrderIndependence"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TemporalOperatorName")
@XmlEnum
public enum TemporalOperatorName {

    @XmlEnumValue("SequentialEnabling")
    SEQUENTIAL_ENABLING("SequentialEnabling"),
    @XmlEnumValue("Disabling")
    DISABLING("Disabling"),
    @XmlEnumValue("Choice")
    CHOICE("Choice"),
    @XmlEnumValue("Interleaving")
    INTERLEAVING("Interleaving"),
    @XmlEnumValue("InterleavingInfo")
    INTERLEAVING_INFO("InterleavingInfo"),
    @XmlEnumValue("Synchronization")
    SYNCHRONIZATION("Synchronization"),
    @XmlEnumValue("SuspendResume")
    SUSPEND_RESUME("SuspendResume"),
    @XmlEnumValue("SequentialEnablingInfo")
    SEQUENTIAL_ENABLING_INFO("SequentialEnablingInfo"),
    @XmlEnumValue("Parallel")
    PARALLEL("Parallel"),
    @XmlEnumValue("OrderIndependence")
    ORDER_INDEPENDENCE("OrderIndependence");  
    private final String value;

    TemporalOperatorName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TemporalOperatorName fromValue(String v) {
        for (TemporalOperatorName c: TemporalOperatorName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
